language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6

before_install:
    - composer self-update

install:
    - composer --prefer-source install

after_install:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover